version: '3'

services:

  app:
    image: flask-fp-app
    build:
      context: ./flask-app
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}


  nginx:
    image: fp-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"


