version: '3.8'

services:

  app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./flask-app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped


  nginx:
    image: fp-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"


