version: '3'

services:

  app:
    image: flask-fp-app
    build:
      context: ./flask-app
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"


  nginx:
    image: fp-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"


